version: 2.1

orbs:
  haskell: haskell-works/haskell-build@4.1.7
  merge-point: haskell-works/merge-point@1.0.0
  gh-pages: sugarshin/gh-pages@0.0.6

workflows:
  multiple-ghc-build:
    jobs:

      - haskell/build-with-cci-cache:
          name: GHC 8.4.4
          executor: haskell/ghc-8_4_4
          context: haskell-ci
          cabal-test-extra: --test-show-details=direct
          after-build: [build-github-pages]

      - merge-point/merge-point:
          name: Build Ok
          requires:
            - GHC 8.4.4

      - gh-pages/deploy:
          build-dir: _site
          requires:
            - Build Ok
          ssh-fingerprints: 'ff:22:gs:v6:gg:2g:22:7j:73:gf:ja:36:ff:y2:22:89'
            
commands:
  build-github-pages:
    description: Deploy master to Github Pages
    steps:
      - run:
          name: Publish github pages
          command: ./bin/publish-github.sh
