version: 2.1

orbs:
  haskell: haskell-works/haskell-build@4.1.7
  merge-point: haskell-works/merge-point@1.0.0

workflows:
  multiple-ghc-build:
    jobs:

      - haskell/build-with-cci-cache:
          name: GHC 8.4.4
          executor: haskell/ghc-8_4_4
          context: haskell-ci
          cabal-test-extra: --test-show-details=direct
          after-build: [build-github-pages]

commands:
  build-github-pages:
    description: Deploy master to Github Pages
    steps:
      - run:
          name: Publish github pages
          command: ./bin/publish-github.sh
