version: 2.1

orbs:
  haskell: haskell-works/haskell-build@4.1.7
  merge-point: haskell-works/merge-point@1.0.0

workflows:
  multiple-ghc-build:
    jobs:

      - haskell/build-with-cci-cache:
          name: GHC 8.4.4
          executor: haskell/ghc-8_4_4
          context: haskell-ci
          cabal-test-extra: --test-show-details=direct

      - merge-point/merge-point:
          name: Build Ok
          requires:
            - GHC 8.4.4

      - deploy:
          name: Deploy master to Github Pages
          command: |
            git config --global user.email robots@circleci.com
            git config --global user.name CircleCI
            cabal exec site rebuild
            git checkout master
            git pull --rebase
            # Overwrite existing files with new files
            cp -a _site/. .
            #  Commit
            git add --all
            git commit -m "[`date '+%F %T %Z'`] New release"
            # Push
            git push origin master:master
